# Generated by Django 2.2 on 2019-04-04 21:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trips',
            name='end_time',
            field=models.DateField(default=datetime.datetime(2019, 4, 4, 21, 50, 13, 822971)),
        ),
        migrations.AddField(
            model_name='trips',
            name='start_time',
            field=models.DateField(default=datetime.datetime(2019, 4, 4, 21, 50, 13, 822926)),
        ),
    ]
