# Generated by Django 2.2 on 2019-04-11 13:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0002_auto_20190404_2150'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('scooter', 'scooter'), ('bike', 'bike')], max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='trips',
            name='end_time',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='trips',
            name='start_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='trips',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rentals.User'),
        ),
        migrations.AlterField(
            model_name='trips',
            name='vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rentals.Vehicle'),
        ),
    ]
