# Generated by Django 2.2 on 2019-04-11 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0003_auto_20190411_1325'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Trips',
            new_name='Trip',
        ),
    ]
