# Generated by Django 2.2 on 2019-04-25 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0005_auto_20190411_1913'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='serial',
            field=models.CharField(default='foobar', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=200),
        ),
    ]
